import type { CategoryDefinition, DataSource } from "../types";

export const categories: CategoryDefinition[] = [
  {
    id: "currency",
    label: "Currency",
    group: "General",
    apiType: "Currency",
    source: "dual",
    icon: "coins",
    description: "Core currency and catalyst exchange markets.",
  },
  {
    id: "fragments",
    label: "Fragments",
    group: "General",
    apiType: "Fragment",
    source: "dual",
    icon: "shapes",
    description: "Fragments, splinters, invitations and related exchange items.",
  },
  {
    id: "wombgifts",
    label: "Wombgifts",
    group: "General",
    apiType: "Wombgift",
    source: "item",
    icon: "gem",
    description: "Wombgift listings and Genesis Tree outcomes.",
  },
  {
    id: "runegrafts",
    label: "Runegrafts",
    group: "General",
    apiType: "Runegraft",
    source: "exchange",
    icon: "sparkles",
    description: "Runegraft currency-exchange prices.",
  },
  {
    id: "allflame-embers",
    label: "Allflame Embers",
    group: "General",
    apiType: "AllflameEmber",
    source: "exchange",
    icon: "flame",
    description: "Current Allflame Ember markets.",
  },
  {
    id: "tattoos",
    label: "Tattoos",
    group: "General",
    apiType: "Tattoo",
    source: "exchange",
    icon: "badge",
    description: "Passive-skill tattoo prices.",
  },
  {
    id: "omens",
    label: "Omens",
    group: "General",
    apiType: "Omen",
    source: "exchange",
    icon: "eye",
    description: "Omen exchange markets.",
  },
  {
    id: "djinn-coins",
    label: "Djinn Coins",
    group: "General",
    apiType: "DjinnCoin",
    source: "exchange",
    icon: "circle-dollar",
    description: "Djinn Coin market prices.",
  },
  {
    id: "ducats",
    label: "Ducats",
    group: "General",
    apiType: "Ducat",
    source: "exchange",
    icon: "medal",
    description: "Ducat exchange rates.",
  },
  {
    id: "enshrouding-crystals",
    label: "Enshrouding Crystals",
    group: "General",
    apiType: "EnshroudingCrystal",
    source: "exchange",
    icon: "diamond",
    description: "Enshrouding Crystal exchange prices.",
  },
  {
    id: "divination-cards",
    label: "Divination Cards",
    group: "General",
    apiType: "DivinationCard",
    source: "exchange",
    icon: "layers",
    description: "Divination card exchange values.",
  },
  {
    id: "artifacts",
    label: "Artifacts",
    group: "General",
    apiType: "Artifact",
    source: "exchange",
    icon: "landmark",
    description: "Expedition artifact exchange prices.",
  },
  {
    id: "oils",
    label: "Oils",
    group: "General",
    apiType: "Oil",
    source: "exchange",
    icon: "droplets",
    description: "Blight oil exchange values.",
  },
  {
    id: "incubators",
    label: "Incubators",
    group: "General",
    apiType: "Incubator",
    source: "item",
    icon: "egg",
    description: "Incubator stash estimates.",
  },
  {
    id: "unique-weapons",
    label: "Unique Weapons",
    group: "Equipment & gems",
    apiType: "UniqueWeapon",
    source: "item",
    icon: "swords",
    description: "Unique weapon variants, links and listings.",
  },
  {
    id: "unique-armours",
    label: "Unique Armours",
    group: "Equipment & gems",
    apiType: "UniqueArmour",
    source: "item",
    icon: "shield",
    description: "Unique armour variants, links and listings.",
  },
  {
    id: "unique-accessories",
    label: "Unique Accessories",
    group: "Equipment & gems",
    apiType: "UniqueAccessory",
    source: "item",
    icon: "ring",
    description: "Unique rings, amulets and belts.",
  },
  {
    id: "unique-flasks",
    label: "Unique Flasks",
    group: "Equipment & gems",
    apiType: "UniqueFlask",
    source: "item",
    icon: "flask",
    description: "Unique flask values and listings.",
  },
  {
    id: "unique-jewels",
    label: "Unique Jewels",
    group: "Equipment & gems",
    apiType: "UniqueJewel",
    source: "item",
    icon: "hexagon",
    description: "Unique jewel prices and variants.",
  },
  {
    id: "forbidden-jewels",
    label: "Forbidden Jewels",
    group: "Equipment & gems",
    apiType: "ForbiddenJewel",
    source: "item",
    icon: "orbit",
    description: "Forbidden Flame and Flesh pair pricing.",
  },
  {
    id: "shrine-belts",
    label: "Shrine Belts",
    group: "Equipment & gems",
    apiType: "ShrineBelt",
    source: "item",
    icon: "crown",
    description: "Shrine belt variants and listings.",
  },
  {
    id: "unique-tinctures",
    label: "Unique Tinctures",
    group: "Equipment & gems",
    apiType: "UniqueTincture",
    source: "item",
    icon: "bottle",
    description: "Unique tincture prices.",
  },
  {
    id: "unique-relics",
    label: "Unique Relics",
    group: "Equipment & gems",
    apiType: "UniqueRelic",
    source: "item",
    icon: "relic",
    description: "Unique relic values and variants.",
  },
  {
    id: "skill-gems",
    label: "Skill Gems",
    group: "Equipment & gems",
    apiType: "SkillGem",
    source: "item",
    icon: "sparkle",
    description: "Gem level, quality, corruption and type prices.",
  },
  {
    id: "imbued-gems",
    label: "Imbued Gems",
    group: "Equipment & gems",
    apiType: "ImbuedGem",
    source: "item",
    icon: "component",
    description: "Imbued gem values and variants.",
  },
  {
    id: "cluster-jewels",
    label: "Cluster Jewels",
    group: "Equipment & gems",
    apiType: "ClusterJewel",
    source: "item",
    icon: "network",
    description: "Cluster jewel bases and enchant variants.",
  },
  {
    id: "maps",
    label: "Maps",
    group: "Atlas",
    apiType: "Map",
    source: "item",
    icon: "map",
    description: "Current Atlas map prices.",
  },
  {
    id: "blighted-maps",
    label: "Blighted Maps",
    group: "Atlas",
    apiType: "BlightedMap",
    source: "item",
    icon: "map-pinned",
    description: "Blighted map tier prices.",
  },
  {
    id: "blight-ravaged-maps",
    label: "Blight-ravaged Maps",
    group: "Atlas",
    apiType: "BlightRavagedMap",
    source: "item",
    icon: "route",
    description: "Blight-ravaged map prices.",
  },
  {
    id: "unique-maps",
    label: "Unique Maps",
    group: "Atlas",
    apiType: "UniqueMap",
    source: "item",
    icon: "map-plus",
    description: "Unique map variants and prices.",
  },
  {
    id: "valdo-maps",
    label: "Valdo Maps",
    group: "Atlas",
    apiType: "ValdoMap",
    source: "item",
    icon: "scroll",
    description: "Valdo's Puzzle Box map rewards.",
  },
  {
    id: "delirium-orbs",
    label: "Delirium Orbs",
    group: "Atlas",
    apiType: "DeliriumOrb",
    source: "exchange",
    icon: "disc",
    description: "Delirium Orb exchange values.",
  },
  {
    id: "invitations",
    label: "Invitations",
    group: "Atlas",
    apiType: "Invitation",
    source: "item",
    icon: "mail-open",
    description: "Atlas invitation prices.",
  },
  {
    id: "scarabs",
    label: "Scarabs",
    group: "Atlas",
    apiType: "Scarab",
    source: "exchange",
    icon: "bug",
    description: "Scarab exchange markets.",
  },
  {
    id: "astrolabes",
    label: "Astrolabes",
    group: "Atlas",
    apiType: "Astrolabe",
    source: "exchange",
    icon: "compass",
    description: "Astrolabe exchange markets.",
  },
  {
    id: "memories",
    label: "Memories",
    group: "Atlas",
    apiType: "Memory",
    source: "item",
    icon: "brain",
    description: "Atlas Memory prices.",
  },
  {
    id: "temples",
    label: "Temples",
    group: "Atlas",
    apiType: "IncursionTemple",
    source: "item",
    icon: "building",
    description: "Chronicle of Atzoatl room values.",
  },
  {
    id: "base-types",
    label: "Base Types",
    group: "Crafting",
    apiType: "BaseType",
    source: "item",
    icon: "anvil",
    description: "Item-level and influenced crafting bases.",
  },
  {
    id: "fossils",
    label: "Fossils",
    group: "Crafting",
    apiType: "Fossil",
    source: "exchange",
    icon: "shell",
    description: "Delve fossil exchange prices.",
  },
  {
    id: "resonators",
    label: "Resonators",
    group: "Crafting",
    apiType: "Resonator",
    source: "exchange",
    icon: "circle-dot",
    description: "Delve resonator exchange prices.",
  },
  {
    id: "beasts",
    label: "Beasts",
    group: "Crafting",
    apiType: "Beast",
    source: "item",
    icon: "paw",
    description: "Bestiary beast prices.",
  },
  {
    id: "essences",
    label: "Essences",
    group: "Crafting",
    apiType: "Essence",
    source: "exchange",
    icon: "flame-kindling",
    description: "Essence exchange values.",
  },
  {
    id: "vials",
    label: "Vials",
    group: "Crafting",
    apiType: "Vial",
    source: "item",
    icon: "test-tube",
    description: "Incursion upgrade vial prices.",
  },
];

export const categoryGroups = [
  "General",
  "Equipment & gems",
  "Atlas",
  "Crafting",
] as const;

export const categoryById = Object.fromEntries(
  categories.map((category) => [category.id, category]),
) as Record<string, CategoryDefinition>;

export function defaultSource(category: CategoryDefinition): DataSource {
  if (category.source === "dual") return "exchange";
  return category.source === "exchange" ? "exchange" : "stash-item";
}

function hasFaustusTransport() {
  if (typeof window === "undefined") return false;
  const runtime = window as Window & {
    poeWidget?: unknown;
    Capacitor?: { isNativePlatform?: () => boolean };
  };
  return Boolean(runtime.poeWidget || runtime.Capacitor?.isNativePlatform?.());
}

export function supportsFaustus(category: CategoryDefinition, transportAvailable = hasFaustusTransport()) {
  return transportAvailable && (category.source === "exchange" || category.source === "dual");
}
