import type { LucideIcon } from "lucide-react";
import {
  Anvil,
  Badge,
  Brain,
  Bug,
  Building2,
  Circle,
  CircleDollarSign,
  CircleDot,
  Compass,
  Component,
  Crown,
  Diamond,
  Disc3,
  Droplets,
  Egg,
  Eye,
  Flame,
  FlameKindling,
  FlaskConical,
  Gem,
  Hexagon,
  Landmark,
  Layers3,
  MailOpen,
  Map,
  MapPinned,
  Medal,
  Network,
  Orbit,
  PawPrint,
  Route,
  ScrollText,
  Shapes,
  Shell,
  Shield,
  Sparkles,
  Swords,
  TestTube,
  Coins,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  coins: Coins,
  shapes: Shapes,
  gem: Gem,
  sparkles: Sparkles,
  sparkle: Sparkles,
  flame: Flame,
  badge: Badge,
  eye: Eye,
  "circle-dollar": CircleDollarSign,
  medal: Medal,
  diamond: Diamond,
  layers: Layers3,
  landmark: Landmark,
  droplets: Droplets,
  egg: Egg,
  swords: Swords,
  shield: Shield,
  ring: Circle,
  flask: FlaskConical,
  hexagon: Hexagon,
  orbit: Orbit,
  crown: Crown,
  bottle: FlaskConical,
  relic: Landmark,
  component: Component,
  network: Network,
  map: Map,
  "map-pinned": MapPinned,
  route: Route,
  "map-plus": MapPinned,
  scroll: ScrollText,
  disc: Disc3,
  "mail-open": MailOpen,
  bug: Bug,
  compass: Compass,
  brain: Brain,
  building: Building2,
  anvil: Anvil,
  shell: Shell,
  "circle-dot": CircleDot,
  paw: PawPrint,
  "flame-kindling": FlameKindling,
  "test-tube": TestTube,
};

export function CategoryIcon({
  name,
  size = 18,
  strokeWidth = 1.8,
}: {
  name: string;
  size?: number;
  strokeWidth?: number;
}) {
  const Icon = icons[name] || Gem;
  return <Icon aria-hidden size={size} strokeWidth={strokeWidth} />;
}
